//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABILITAZIONE
    {
        public string SIGLA { get; set; }
        public string MATR_UTENTE { get; set; }
        public System.DateTime DATA_INS { get; set; }
        public System.DateTime DATA_VAR { get; set; }
        public string RICH_EQUIP_CONDOTTA { get; set; }
        public string RICH_EQUIP_CABINA { get; set; }
    }
}
